language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer self-update
    - composer install --dev
    #- pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - ./bin/phpunit -v
    # - phpcs ./src/HieblMedia/Encryption/Encrypter.php --standard=PSR2 --report=summary -np
