language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - pear install pear/PHP_CodeSniffer
    - composer self-update
    - composer install --dev

script:
    - ./bin/phpunit -v
    - phpcs .\src\Encryption\Encrypter.php --standard=PSR2 --report=summary -np
